"""Statistical analysis of the LAWE-IDS ablation study.

Tests whether the five ablation conditions differ significantly. The paper's
claim is that base-learner *diversity* drives performance, not the fusion
mechanism: a non-significant difference between conditions supports this.

Design
------
- Treatments  : the 5 ablation conditions.
- Blocks      : each (dataset, seed) pair is one block.
- Metrics     : accuracy and F1 (run independently).

Tests
-----
1. Friedman test across all 5 conditions (omnibus, blocked by dataset[,seed]).
2. Wilcoxon signed-rank post-hoc: Full LAWE-IDS vs each other condition.
   (Holm-Bonferroni correction over the 4 comparisons.)
3. Descriptive mean +/- std per condition and mean delta vs Full.

Outputs a console report and a LaTeX-ready table to results/.

Usage
-----
    python analyze_ablation_stats.py
"""
import os
import numpy as np
import pandas as pd
from scipy.stats import friedmanchisquare, wilcoxon

from config import RESULTS_DIR

CONDITIONS = [
    'Full LAWE-IDS',
    'No Feature Gating',
    'Fixed Weights',
    'No Self-Attention',
    'No CatBoost',
]
REFERENCE = 'Full LAWE-IDS'
METRICS = ['accuracy', 'f1']


def holm_bonferroni(pvals):
    """Return Holm-Bonferroni adjusted p-values, preserving input order."""
    pvals = np.asarray(pvals, dtype=float)
    m = len(pvals)
    order = np.argsort(pvals)
    adj = np.empty(m, dtype=float)
    running = 0.0
    for rank, idx in enumerate(order):
        val = (m - rank) * pvals[idx]
        running = max(running, val)
        adj[idx] = min(running, 1.0)
    return adj


def build_block_matrix(df, metric):
    """Pivot to a block x condition matrix; rows are complete blocks only."""
    block_cols = ['dataset', 'seed'] if 'seed' in df.columns else ['dataset']
    wide = df.pivot_table(index=block_cols, columns='condition', values=metric)
    wide = wide.reindex(columns=CONDITIONS)
    complete = wide.dropna(axis=0, how='any')
    return complete


def analyse_metric(df, metric):
    block = build_block_matrix(df, metric)
    n_blocks = len(block)
    report = {'metric': metric, 'n_blocks': n_blocks}

    # Descriptive stats
    desc = {}
    for cond in CONDITIONS:
        vals = block[cond].to_numpy()
        delta = (block[cond] - block[REFERENCE]).to_numpy()
        desc[cond] = dict(
            mean=vals.mean(), std=vals.std(ddof=1) if n_blocks > 1 else 0.0,
            mean_delta_vs_full=delta.mean(),
            max_abs_delta=np.abs(delta).max(),
        )
    report['descriptive'] = desc

    # Friedman omnibus
    cols = [block[c].to_numpy() for c in CONDITIONS]
    fr_stat, fr_p = friedmanchisquare(*cols)
    report['friedman'] = dict(stat=fr_stat, p=fr_p)

    # Wilcoxon post-hoc: Full vs each other condition
    others = [c for c in CONDITIONS if c != REFERENCE]
    raw_p, stats = [], {}
    for cond in others:
        a = block[REFERENCE].to_numpy()
        b = block[cond].to_numpy()
        if np.allclose(a, b):
            w, p = np.nan, 1.0
        else:
            try:
                w, p = wilcoxon(a, b)
            except ValueError:
                w, p = np.nan, 1.0
        raw_p.append(p)
        stats[cond] = dict(stat=w, p_raw=p)
    adj = holm_bonferroni(raw_p)
    for cond, ap in zip(others, adj):
        stats[cond]['p_holm'] = ap
    report['wilcoxon'] = stats
    return report


def print_report(rep):
    m = rep['metric'].upper()
    n = rep['n_blocks']
    print(f"\n{'='*68}\n  {m}  (N = {n} blocks)\n{'='*68}")

    print(f"\n  Per-condition (mean +/- std over blocks):")
    print(f"  {'Condition':<20} {'mean':>9} {'std':>9} {'Δ vs Full':>11} {'max|Δ|':>9}")
    for cond in CONDITIONS:
        d = rep['descriptive'][cond]
        print(f"  {cond:<20} {d['mean']*100:>8.3f}% {d['std']*100:>8.3f}% "
              f"{d['mean_delta_vs_full']*100:>+10.3f}% {d['max_abs_delta']*100:>8.3f}%")

    fr = rep['friedman']
    sig = 'SIGNIFICANT' if fr['p'] < 0.05 else 'not significant'
    print(f"\n  Friedman omnibus: chi2 = {fr['stat']:.3f}, p = {fr['p']:.4f}  ({sig})")

    print(f"\n  Wilcoxon post-hoc (Full vs variant, Holm-corrected):")
    print(f"  {'Comparison':<28} {'p_raw':>9} {'p_holm':>9}")
    for cond, s in rep['wilcoxon'].items():
        praw = '  n/a  ' if np.isnan(s['p_raw']) else f"{s['p_raw']:.4f}"
        pholm = f"{s['p_holm']:.4f}"
        mark = ' *' if s['p_holm'] < 0.05 else ''
        print(f"  Full vs {cond:<20} {praw:>9} {pholm:>9}{mark}")


def emit_latex(reports, path):
    acc = reports['accuracy']
    f1 = reports['f1']
    lines = []
    lines.append("% Auto-generated by analyze_ablation_stats.py")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Ablation conditions with statistical comparison against "
                 "the full model. Values are mean$\\pm$std across "
                 f"{acc['n_blocks']} (dataset, seed) blocks. "
                 "$p$-values from Wilcoxon signed-rank tests "
                 "(Holm-corrected), reference = Full LAWE-IDS.}")
    lines.append("\\label{tab:ablation_stats}")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("Condition & Accuracy (\\%) & $\\Delta$Acc & F1 (\\%) & $p_{\\text{Holm}}$(F1) \\\\")
    lines.append("\\midrule")
    for cond in CONDITIONS:
        da = acc['descriptive'][cond]
        df1 = f1['descriptive'][cond]
        if cond == REFERENCE:
            pstr = '--'
        else:
            ph = f1['wilcoxon'][cond]['p_holm']
            pstr = f"{ph:.3f}"
        lines.append(
            f"{cond} & {da['mean']*100:.3f}$\\pm${da['std']*100:.3f} & "
            f"{da['mean_delta_vs_full']*100:+.3f} & "
            f"{df1['mean']*100:.3f}$\\pm${df1['std']*100:.3f} & {pstr} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    fr_acc = acc['friedman']
    fr_f1 = f1['friedman']
    lines.append("\\par\\smallskip")
    lines.append(
        f"\\footnotesize Friedman omnibus: accuracy $\\chi^2={fr_acc['stat']:.2f}$, "
        f"$p={fr_acc['p']:.3f}$; F1 $\\chi^2={fr_f1['stat']:.2f}$, $p={fr_f1['p']:.3f}$.")
    lines.append("\\end{table}")
    with open(path, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')


def main():
    csv = os.path.join(RESULTS_DIR, 'lawe_ablation_results.csv')
    df = pd.read_csv(csv)
    if 'seed' not in df.columns:
        df['seed'] = 42
    seeds = sorted(df['seed'].unique())
    datasets = sorted(df['dataset'].unique())
    print(f"Loaded {len(df)} ablation rows | seeds={seeds} | datasets={datasets}")
    if len(seeds) == 1:
        print("WARNING: only one seed present. Tests use datasets as blocks (N=%d); "
              "low power. Re-run ablation for more seeds to strengthen." % len(datasets))

    reports = {}
    for metric in METRICS:
        rep = analyse_metric(df, metric)
        reports[metric] = rep
        print_report(rep)

    out = os.path.join(RESULTS_DIR, 'ablation_stats_table.tex')
    emit_latex(reports, out)
    print(f"\nLaTeX table written to {out}")


if __name__ == '__main__':
    main()
